Add support of passing Kafka header when producing
bitleak/kaproxy pull request #11
Opened 2023-04-26 08:05 UTC by fanghq2018

Support Kafka header passthrough, which can be used to transmit trace ID.

2023-04-26 08:16 UTC, git-hulk commented
Hi @xiangzi1113 @fishery86 please take a look while you're free

2023-04-26 10:44 UTC, xiangzi1113 commented
Suggestion: Discard BatchProduceWithJson(), and instead extend BatchProduce(), transmitting trace information through the header

2023-04-28 15:34 UTC, fishery86 requested changes

2023-04-28 15:34 UTC, fishery86 commented on server/produce_handler.go
> +}
Extract duplicate code as methods instead of copying

2023-05-11 06:20 UTC, merged